# fly.toml app configuration file generated for jmakela-elixir-protohackers on 2023-11-30T11:46:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "jmakela-elixir-protohackers"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "arn"

[build]

[[services]]
  http_checks = []
  internal_port = 4020
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 100
    soft_limit = 80
    type = "connections"

  # [[services.ports]]
  #   handlers = []
  #   port = "4000"

  # [[services.ports]]
  #   handlers = []
  #   port = "4010"

  [[services.ports]]
    handlers = []
    port = "4020"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
